<?php ob_start() ?>

    <section>
        <a class="button ajout" title="Ajout de catégorie" href="stillCatForm">Ajouter une catégorie</a>

        <p class="messageTable">Veuillez vous connecter sur un écran de taille adapté(tablette ou ordinateur) pour
            visualiser correctement cette page.</p>

        <?php if (!empty($categories)): ?>
            <table>
                <thead>
                <tr>
                    <th>Catégorie</th>
                    <th>Photo de Couverture</th>
                    <th>Modifier</th>
                    <th>Supprimer</th>
                </tr>
                </thead>
                <tbody>

                <?php foreach ($categories as $categorie): ?>
                    <tr>
                        <td><?= $categorie["categorie"] ?></td>

                        <td><img class="miniPhoto"
                                 src="assets/images/stillLife/<?= $categorie["categorie"] ?>/<?= $categorie["photoCouv"] ?>">
                        </td>

                        <td><a href="stillCatForm&id=<?= $categorie["id"] ?>" class="button update"><i
                                        class="fas fa-feather-alt"></i></a></td>

                        <td><a href="stillCatDelete&id=<?= $categorie["id"] ?>" class="button delete"><i
                                        class="fas fa-trash-alt"></i></a></td>
                    </tr>
                <?php endforeach; ?>

                </tbody>
            </table>
        <?php endif; ?>

    </section>

<?php $content = ob_get_clean(); ?>