<?php ob_start() ?>

    <section>
        <a class="button ajout" title="Ajout de photo" href="persoPhotoForm">Ajouter des photos</a>

        <p class="messageTable">Veuillez vous connecter sur un écran de taille adapté(tablette ou ordinateur) pour
            visualiser correctement cette page.</p>

        <?php if (!empty($photoPerso)): ?>
            <table>
                <thead>
                <tr>
                    <th class="titre">Titre</th>
                    <th>Photo</th>
                    <th>Categorie</th>
                    <th>Position</th>
                    <th>Modifier</th>
                    <th>Supprimer</th>
                </tr>
                </thead>

                <tbody>

                <?php foreach ($photoPerso as $photo): ?>
                    <tr>
                        <td class="titre"><p><?= $photo["titre"] ?></p></td>

                        <td><img class="miniPhoto"
                                 src="assets/images/personal/<?= $photo["categorie"]."/".$photo["photo"] ?>"></td>

                        <td><?= $photo["categorie"] ?></td>

                        <td><?php if ($photo["classement"] != 99): ?><?= $photo["classement"] ?><?php endif; ?></td>

                        <td><a href="persoPhotoForm&id=<?= $photo["id"] ?>" class="button update"><i
                                        class="fas fa-feather-alt"></i></a></td>

                        <td><a href="persoPhotoDelete&id=<?= $photo["id"] ?>" class="button delete"><i
                                        class="fas fa-trash-alt"></i></a></td>
                    </tr>
                <?php endforeach ?>

                </tbody>
            </table>
        <?php endif; ?>

    </section>

<?php $content = ob_get_clean(); ?>