<?php ob_start() ?>

<section class="contact">

    <h1>Clémentine Passet</h1>
    <h2>Paris based photographer</h2>
    <img alt="autoportrait de Clémentine Passet photographe"
         src="assets/images/CLEMENTINE_PASSET_AUTOPORTRAIT_024-3.jpg">
    <nav>
        <a href="https://www.instagram.com/clementinepasset/?hl=fr"><i class="fab fa-instagram"></i>instagram</a>
        <a href="mailto:clementine.passet@gmail.com"><i class="far fa-envelope"></i>clementine.passet@gmail.com</a>
        <a href="tel:+33781532626"><i class="fas fa-mobile-alt"></i> +33781532626</a>

    </nav>

</section>

<?php $content = ob_get_clean(); ?>
